/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        surface: '#0c150f',
        'surface-dim': '#0c150f',
        'surface-bright': '#323c34',
        'surface-container-lowest': '#07100a',
        'surface-container-low': '#141e17',
        'surface-container': '#18221b',
        'surface-container-high': '#232c25',
        'surface-container-highest': '#2d3730',
        'on-surface': '#dae5da',
        'on-surface-variant': '#b9cbbc',
        'inverse-surface': '#dae5da',
        'inverse-on-surface': '#29332b',
        outline: '#849587',
        'outline-variant': '#3b4a3f',
        'surface-tint': '#00e38b',
        primary: '#f4fff3',
        'on-primary': '#00391f',
        'primary-container': '#00ff9d',
        'on-primary-container': '#007143',
        'inverse-primary': '#006d40',
        secondary: '#c8c5ca',
        'on-secondary': '#303033',
        'secondary-container': '#47464a',
        'on-secondary-container': '#b7b4b8',
        tertiary: '#fefbff',
        'on-tertiary': '#303035',
        'tertiary-container': '#e1dee5',
        'on-tertiary-container': '#636268',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#56ffa8',
        'primary-fixed-dim': '#00e38b',
        'on-primary-fixed': '#002110',
        'on-primary-fixed-variant': '#00522f',
        'secondary-fixed': '#e4e1e6',
        'secondary-fixed-dim': '#c8c5ca',
        'on-secondary-fixed': '#1b1b1e',
        'on-secondary-fixed-variant': '#47464a',
        'tertiary-fixed': '#e4e1e8',
        'tertiary-fixed-dim': '#c8c5cc',
        'on-tertiary-fixed': '#1b1b20',
        'on-tertiary-fixed-variant': '#47464c',
        background: '#0c150f',
        'on-background': '#dae5da',
        'surface-variant': '#2d3730',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        base: '8px',
        gutter: '24px',
        'margin-mobile': '16px',
        'margin-desktop': '40px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
      fontFamily: {
        'display-lg': ['Sora', 'sans-serif'],
        'display-lg-mobile': ['Sora', 'sans-serif'],
        'headline-md': ['Sora', 'sans-serif'],
        'headline-sm': ['Sora', 'sans-serif'],
        'body-lg': ['"Hanken Grotesk"', 'sans-serif'],
        'body-md': ['"Hanken Grotesk"', 'sans-serif'],
        'label-mono': ['"JetBrains Mono"', 'monospace'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '800' }],
        'display-lg-mobile': ['36px', { lineHeight: '1.1', fontWeight: '800' }],
        'headline-md': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-sm': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-mono': ['14px', { lineHeight: '1.0', letterSpacing: '0.05em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
}
